### ISSUE TITLE
Soliciting advice

### ISSUE THREAD

**Issue by coder0xff** [SamsamTS/CS-MoveIt#1]
Hi. Sorry, I know this is not the correct place for this, but I haven't had much luck in the reddit community or the so-called API reference wiki, and I'd really like to make a mod for Cities: Skylines. I'm a professional developer, so I can handle myself, but I've spent hours tinkering with NetManager to no avail. I'd like to make new road segments procedurally. If you have any advice I'd hugely appreciate it. Do you have notes on the undocumented APIs that you could share? Sorry, again, and thanks for reading my request.

Cheers,
coder0xff

**Comment by SamsamTS** [comment]
Sorry for the late reply. I was still figuring out how to do it myself at the time.

To create a segment you need to create the nodes first with CreateNode
https://github.com/SamsamTS/CS-MoveIt/blob/master/MoveIt/Moveable.cs#L1309

Then connect them CreateSegment
https://github.com/SamsamTS/CS-MoveIt/blob/master/MoveIt/Moveable.cs#L1358

Hope this help.
