### ISSUE TITLE
Transport routes appearing when using Move It

### ISSUE THREAD

**Issue by originalfoo** [SamsamTS/CS-MoveIt#11]
For some reason transport routes (like bus routes and train routes) are being visualised whilst using Move It. While this is often useful, it makes detailing on roads very difficult because often the transport route will block visibility of the decal I'm moving.

Would it be possible to get an option to toggle whether routes are shown or not?

Note: I have >80 mods active so if this isn't something that happens for everyone lmk and I'll try and work out which external mod causes the issue.

**Comment by SamsamTS** [comment]
This is not normal. I cannot reproduce. Another mod must be conflicting.

**Comment by originalfoo** [comment]
Ok, I'll see if I can track down the offending mod and report back.

**Comment by originalfoo** [comment]
First batch of disabled mods seems to have solved the problem, so it's one of the following mods as far as I can tell:

* Transport Line Rendering Fix
* Toggleable Whiteness
* District Stats
* Advanced Toolbar
* Advanced Stop Selection

My guess is it's **Toggleable Whiteness** or maybe **Transport Line Rendering Fix**.

It takes me about 1 hour to load/exit a save so it may be a few days before I test each of the mods listed above in isolation.

**Comment by originalfoo** [comment]
Looking at mod description for [Toggleable Whiteness](https://steamcommunity.com/sharedfiles/filedetails/?id=465318661&searchtext=toggleable+whiteness) a recent update mentions improved compatibility with Move It so almost certain that's the culprit mod.

**Comment by originalfoo** [comment]
Confirmed as Toggleabe Whiteness mod, will report in it's issue tracker.

**Comment by SamsamTS** [comment]
Does it still happens? MoveItTool no longer inherits TransportTool which I believe was the source of multiple issues with some BP mods.

**Comment by originalfoo** [comment]
Confirmed fixed :D Thank you!
