### ISSUE TITLE
Remove selected items

### ISSUE THREAD

**Issue by Ciantic** [SamsamTS/CS-MoveIt#2]
Even though there is bulldozer mods, I think deleting selected items fits to this mod since it shows the selected items very nicely (compared to many bulldozing mods).

I've noticed that some do a huge collection of items in area outside, then copy & paste it elsewhere. There is one problem with this however, there is no easy way to remove the selected items.

**Comment by SamsamTS** [comment]
It seems like a popular request. The reason I didn't add that already is because of the undo/redo, I'm not sure i'm able to make undo work with deleting in the current state of the mod and might mess up the undo queue. I need some time to figure out a solution.
