### ISSUE TITLE
[Feature] Flatten / Make same level tool

### ISSUE THREAD

**Issue by lisa-lionheart** [SamsamTS/CS-MoveIt#4]
Hey, great mod!

Typically I use to move it to adjust the vertical heights on bridges and train lines when making new routes as by default the game makes them go up and down almost randomly

Would it be possible to add an option when selecting several nodes to move them to all be at the same vertical level?

Perhaps choosing to go to the lowest, the highest or an average of all the heights?

**Comment by originalfoo** [comment]
I came here to ask for same thing, would be super-useful when working with roads and I want to make the nodes all the same level to get perfectly flat road.

Ideally I'd like the level to be set by the first selected node as that allows me to specifically define the level I want for all the other nodes. The alternatives mentioned in OP (average, highest, lowest) would also be useful, but most of the time, personally, I'd want first selected node to define the level.

**Comment by originalfoo** [comment]
Scope creep: Tool to "smooth" selected nodes, based on order in which the nodes are shift-selected. For example, I have a wobbly road going up a hill (despite using features of fine road heights tool, etc., roads sometimes end up wobbly) - I could select each node in turn and click a button and automagically the incline of the road becomes perfectly smooth.

**Comment by originalfoo** [comment]
Just wanted to say thanks for adding the feature - the implementation is far better than I could have imagined, and it works extremely well!
